files:
  - source: /docs/en/**/*.md
    translation: /docs/CROWDIN/%two_letters_code%/**/%original_file_name%
  - source: /docs/en/*.py
    translation: /docs/CROWDIN/%two_letters_code%/%original_file_name%
